# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# 
# Let us list the factors of the first seven triangle numbers:
# 
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# 
# What is the value of the first triangle number to have over five hundred divisors?

class Fixnum
  
  def factors
    arr=[]
    (1..Math.sqrt(self)).each do |x| 
      if self % x == 0
        arr << self/x
        arr << x
      end
    end
    arr.uniq.sort
  end
  
  def natural
    self.downto(1).inject(0,:+)
  end
     
  def checkin
    (1..self).each do |x| 
      return x.natural if x.natural.factors.length > 500
    end 
  end
  
end



now = Time.now
999999.checkin # => 76576500
later = Time.now
later-now # => 16.194509
